baseURL = "https://TheKK.github.io"
languageCode = "zh-tw"
title = "KK'S NOTE"
theme = "hyde-hyde"
googleAnalytics = "Your google analytics tracking ID - optional"
disqusShortname = "new-kks-note"

[params]
author = "TheKK"
title = "KK's NOTE"
description = "Program/Game/Cat/Rust/C++"

homeimg = "URL to the image used for the home button at the bottom of each post - optional"
bgimg = "URL to the image used for the page background - optional"

highlightjs = true
highlightjsstyle = "github"

[params.social]
github = "thekk"

[[menu.main]]
name = "Posts"
weight = 100
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/aboutme/"
