# Originally copy-paste from https://github.com/srid/rib with license of BSD 3-Clause.

name: "Publish"
on:
  # Run only when pushing to neuron branch
  push:
    branches:
      - neuron
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v6
      with:
        name: srid
    # This builds neuron, as well as run tests
    - name: Install neuron 
      run: nix-env -j 4 -if https://github.com/srid/neuron/archive/master.tar.gz 
    - name: Build neuron site 🔧
      run: |
        neuron --version
        neuron rib
    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: .neuron/output
